/* Generated file - do not edit */
/* src/actions.c */
/* src/ai.c */
/* src/calls.c */
#define call_generic (dll_body_functions->call_generic)
/* src/construct.c */
/* src/crogue.c */
#define timepass (dll_body_functions->timepass)
/* src/draw.c */
#define full_redraw (dll_body_functions->full_redraw)
#define draw_tile (dll_body_functions->draw_tile)
/* src/facing.c */
/* src/files.c */
/* src/huffman.c */
/* src/interpret.c */
/* src/interpret_aux.c */
/* src/items.c */
#define give_item (dll_body_functions->give_item)
#define itemname (dll_body_functions->itemname)
#define identify_type (dll_body_functions->identify_type)
#define place_item (dll_body_functions->place_item)
#define top_item (dll_body_functions->top_item)
#define randitem (dll_body_functions->randitem)
/* src/light.c */
#define illuminate (dll_body_functions->illuminate)
/* src/magic.c */
/* src/messagefield.c */
#define message (dll_body_functions->message)
/* src/mkmap.c */
#define make_door (dll_body_functions->make_door)
/* src/monst.c */
#define monstbytile (dll_body_functions->monstbytile)
#define monstname (dll_body_functions->monstname)
#define addmonster (dll_body_functions->addmonster)
#define monst_takedamage (dll_body_functions->monst_takedamage)
#define monst_heal (dll_body_functions->monst_heal)
#define monst_is_peaceful (dll_body_functions->monst_is_peaceful)
#define scare_monster (dll_body_functions->scare_monster)
#define scare_monster_force (dll_body_functions->scare_monster_force)
#define confuse_monster (dll_body_functions->confuse_monster)
/* src/options.c */
#define get_option (dll_body_functions->get_option)
/* src/pet.c */
/* src/player.c */
#define apply_stat_mod_desc (dll_body_functions->apply_stat_mod_desc)
#define update_player (dll_body_functions->update_player)
#define follow_connection (dll_body_functions->follow_connection)
#define goto_level (dll_body_functions->goto_level)
#define place_player_randomly (dll_body_functions->place_player_randomly)
#define plr_mod_stat (dll_body_functions->plr_mod_stat)
#define plr_restore_stat (dll_body_functions->plr_restore_stat)
/* src/rand.c */
#define xrandom (dll_body_functions->xrandom)
#define nrandom (dll_body_functions->nrandom)
#define lrand (dll_body_functions->lrand)
/* src/rle.c */
/* src/score.c */
/* src/skill.c */
/* src/spell.c */
/* src/throw.c */
/* src/tilefield.c */
#define UI_TF_DrawEffect (dll_body_functions->UI_TF_DrawEffect)
#define UI_TF_ClearEffects (dll_body_functions->UI_TF_ClearEffects)
/* src/tiles.c */
/* src/timer.c */
#define add_timer (dll_body_functions->add_timer)
/* src/use.c */
/* src/util.c */
#define retprintf (dll_body_functions->retprintf)
#define trace_path (dll_body_functions->trace_path)
#define find_monster_description (dll_body_functions->find_monster_description)
#define deref_file_ptr (dll_body_functions->deref_file_ptr)
#define deref_file_ptr_partial (dll_body_functions->deref_file_ptr_partial)
#define isNull (dll_body_functions->isNull)
/* sys/stub/graph.c */
#define Graph_ClrScr (dll_body_functions->Graph_ClrScr)
#define Graph_DrawChar (dll_body_functions->Graph_DrawChar)
#define Graph_DrawStr (dll_body_functions->Graph_DrawStr)
#define Graph_ClearRect (dll_body_functions->Graph_ClearRect)
/* sys/stub/main.c */
/* sys/stub/menu.c */
#define UI_Menu_Set_Persist (dll_body_functions->UI_Menu_Set_Persist)
#define UI_Menu_Pick (dll_body_functions->UI_Menu_Pick)
/* sys/stub/prompt.c */
#define prompt (dll_body_functions->prompt)
#define prompt_dir (dll_body_functions->prompt_dir)
/* sys/stub/sysutil.c */
#define read_char (dll_body_functions->read_char)
#define delay (dll_body_functions->delay)
#define UI_Dialog_Default (dll_body_functions->UI_Dialog_Default)
#define UI_Dialog_Display (dll_body_functions->UI_Dialog_Display)
#define FontHeight (dll_body_functions->FontHeight)
#define FontWidth (dll_body_functions->FontWidth)
#define get_keyname (dll_body_functions->get_keyname)
