##
## Makefile.config
##
## Options controlling build. Set non-platform-specific tool paths and options
## here. Options for a specific target go in the file for that target.
##
## See also: Makefile.calc, Makefile.comp
##

PROJECT=CalcRogue
VERSION=Beta 6c

##
## Language setting. Only set once a translation catalog is available in lang/.
##
LANGUAGE=ENGLISH
LANGFILE=lang/english.po
#LANGUAGE=CZECH
#LANGFILE=lang/czech.po

##
## Set to 1 to get a lot more output from make
##
BUILD_VERBOSE := 0

include auto/configure.mk

